name: Build Kapzuul CLI

on:
  push:
    tags: 'v*'
  pull_request:
    branches: [main]

jobs:
  build-kapzuul-cli:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Build binary
        run: |
          go build -o kapzuul_debian11_amd64 -ldflags="-X 'main.gitSha=${{ github.sha }}' -X 'main.version=${{ github.ref_name }}'"  ./cmd/kapzuul

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            kapzuul_debian11_amd64
            install-kapzuul.sh